### ISSUE TITLE
Attempting to perform 3D deformable registration

### ISSUE THREAD

**Issue by stevenagl12** [siavashk/pycpd#29]
I have tried running your code using a trimesh import of a 3D mesh object. However, the code breaks saying that this only works on 2D numpy arrays? How do you perform 3D registrations if it's only able to work with 2D arrays?

**Comment by siavashk** [comment]
The code doesn't "break", rather it raises a ValueError. This is deliberate because the original coherent point drift [paper](https://arxiv.org/pdf/0905.2635.pdf) uses 2D matrices as a containers for point clouds. See page 2, Section 3:

> Throughout the paper we use the following notations:
> ... X_{NxD} ...  the first point set (data points)
> Y_{MxD} ... the second point set (GMM centroids)

This basically means that each row in the 2D array corresponds to one point in the point cloud. The first, second and third columns contain the positions of points along the x, y and z axes respectively.

I have already provided a 3D registration example. See this [section](https://github.com/siavashk/pycpd#usage) of the README. You can try it by running `python examples/fish_{Transform}_3D.py` from the project root.

**Comment by stevenagl12** [comment]
How do you come up with the GMM centroids for your 3d model for X then?

**Comment by siavashk** [comment]
The GMM centroids are the same as the moving (or source) point cloud.
