### ISSUE TITLE
pycpd package citation

### ISSUE THREAD

**Issue by BramshQamar** [siavashk/pycpd#55]
Hello,

I am using pycpd in my work and want to acknowledge pycpd package by citing it. 
Apart from the original CPD paper by Myronenko and Song, is there any publication associated with the implementation of CPD (pycpd package)? 

Thank you,
Bramsh

**Comment by siavashk** [comment]
@gattia if you are willing to do the leg work and be the first author on this I am game. I can review it as a second author.
I have a partially torn MCL and ACL injury and am barely functional right now.

**Comment by gattia** [comment]
@siavashk Sorry to hear about the knee! I'm glad that it's only partially torn - hopefully, the recovery is quick. 

As for the paper, that sounds great. I don't think the JOSS papers are very long. I'll take a peak at the requirements and things and I'll put something together in the coming weeks.

**Comment by siavashk** [comment]
Sounds good!

**Comment by gattia** [comment]
@siavashk I have been preparing the JOSS submission. The list of requirements for the submission can be found here: https://joss.readthedocs.io/en/latest/review_checklist.html

The only thing that is missing at the moment is more explicit documentation. I think just building automated docs from the docstrings would be sufficient. 

I've already made a [pull request](https://github.com/siavashk/pycpd/pull/56) for adding a code of conduct (another requirement). 

If you can take a peak at the compiled PDF paper that I've drafted ([here](https://github.com/siavashk/pycpd/blob/JOSS/JOSS_Submission/paper.pdf)) that would be great. The [paper](https://github.com/siavashk/pycpd/blob/JOSS/JOSS_Submission/paper.md) and [bibliography](https://github.com/siavashk/pycpd/blob/JOSS/JOSS_Submission/paper.bib) files can be updated as you see fit. Please do feel free to edit as much as is necessary. 

Im not sure what I did... but I somehow ended up making the JOSS changes on a weird branch that is behind the master branch. I don't think this is an issue because technically we are allowed to just delete this branch after the review - if we wish.

**Comment by siavashk** [comment]
Thanks @gattia. I will review it. I have covid on top of my injury so it will be a couple of days before I can review it.

**Comment by gattia** [comment]
@siavashk I hope the recovery has gone smoothly! Just checking in here to see if you've had a chance to review this.

**Comment by siavashk** [comment]
@gattia I merged the pull request. I thought that was it! Sorry, I will review it today.
I am doing well. I had two months of physiotherapy but now I am back on my feet again. Thank you for asking. :)

**Comment by siavashk** [comment]
@gattia Looks well. Just one minor comment:
"However, no open-source python version previously existed." should be "However, to the best of our knowledge, no open-source ..."

**Comment by gattia** [comment]
@BramshQamar its been a while since you posted! but we now have a paper that you can cite - while this project might be passed, please keep it in mind for future work. (checkout the readme for the DOI/Link, or you can visit here https://joss.theoj.org/papers/10.21105/joss.04681) 

Thanks @siavashk for all the wor on the repository at large, and getting the paper out! 🎉🥳🍾
