### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by a2mattreed** [siavashk/pycpd#81]
Thanks for this fantastic and well-coded library.  One problem: I found that DeformableRegistration().transform_point_cloud is raising an exception when the number of points to be transformed is different from those used to compute the registration. one of the examples triggers this:

% python examples/fish_deformable_3D_register_with_subset_of_points.py
Traceback (most recent call last):
  File "<snip>/fish_deformable_3D_register_with_subset_of_points.py", line 55, in <module>
    main()
  File "<snip>pycpd-master/examples/fish_deformable_3D_register_with_subset_of_points.py", line 43, in main
    YT = reg.transform_point_cloud(Y=Y)
  File "<snip>/lib/python3.9/site-packages/pycpd/deformable_registration.py", line 68, in transform_point_cloud
    return Y + np.dot(self.G, self.W)
ValueError: operands could not be broadcast together with shapes (182,3) (91,3)

**Comment by gattia** [comment]
Thanks for the feedback! It looks like you  might be using an old version (maybe installed via pypi? - sorry, this probably hasn't been updated in a while). I say that because if you look at the code on the lines you are throwing errors the code doesn't match: 

https://github.com/siavashk/pycpd/blob/e5ca02d2501fb4b633c1664de939c336ffa2349e/pycpd/deformable_registration.py#L68-L100

Can you trying installing from source? Or if you are, can you maybe update? 

Thanks.

**Comment by a2mattreed** [comment]
Wow! Thanks for the amazing fast response. Indeed I’d installed from pypi using pip, but also had the source on hand, so swapped that in and it’s all good. I really  appreciate your work on this library!

 —Matt

**Comment by gattia** [comment]
Glad it worked as expected with the source!

We'll work at updating the pypi version so others dont have this issue. Thanks!
